# Generated by Django 6.0.2 on 2026-04-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
