# Generated by Django 6.0.2 on 2026-04-02 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('term_lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowTermLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('other_term_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_by_lessons', to='term_lesson.termlesson')),
                ('term_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_lessons', to='term_lesson.termlesson')),
            ],
        ),
    ]
