# Generated by Django 6.0.2 on 2026-04-02 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('term_lesson', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=500)),
                ('invitation_code', models.CharField(blank=True, max_length=12, unique=True)),
                ('max_size', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_groups', to=settings.AUTH_USER_MODEL)),
                ('term_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='term_lesson.termlesson')),
            ],
        ),
    ]
