# Generated by Django 6.0.2 on 2026-04-02 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('term_lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('is_final_report', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('term_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='term_lesson.termlesson')),
            ],
        ),
    ]
