# Generated by Django 6.0.2 on 2026-03-26 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('term_lesson', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermLessonStudent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('midterm', models.IntegerField()),
                ('final', models.IntegerField()),
                ('make_up', models.IntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_lesson_students', to=settings.AUTH_USER_MODEL)),
                ('term_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_lesson_students', to='term_lesson.termlesson')),
            ],
        ),
    ]
