# Generated by Django 6.0.2 on 2026-04-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group_project', '0001_initial'),
        ('report', '0002_alter_report_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='project_reports/')),
                ('plagiarism_file', models.FileField(blank=True, null=True, upload_to='plagiarism_reports/')),
                ('is_submitted', models.BooleanField(default=False)),
                ('plagiarism_rate', models.FloatField(default=0.0)),
                ('version', models.IntegerField(default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reports', to='group_project.groupproject')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reports', to='report.report')),
            ],
        ),
    ]
