# Generated by Django 6.0.2 on 2026-05-14 08:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_project', '0001_initial'),
        ('project_report', '0001_initial'),
        ('report', '0002_alter_report_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_reports', to='group_project.groupproject'),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_reports', to='report.report'),
        ),
    ]
