# Generated by Django 6.0.2 on 2026-05-14 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_project', '0001_initial'),
        ('project_report', '0002_projectreport_created_at_alter_projectreport_project_and_more'),
        ('report', '0002_alter_report_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='project_reports/'),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reports', to='group_project.groupproject'),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reports', to='report.report'),
        ),
    ]
