# Generated by Django 6.0.2 on 2026-05-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='type',
            field=models.CharField(choices=[('Devlet', 'Devlet'), ('Vakıf', 'Vakıf')], default='Devlet', max_length=10),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
